---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-intro"
      label: "Intro"
      solveButton: false
    - name: "02-quadlets"
      label: "Quadlets"
      solveButton: false
    - name: "03-systemroles"
      label: "Systemroles"
      solveButton: false

tabs:
  - name: "RHEL"
    url: /wetty_rhel/ssh/root
  - name: "containerhost"
    url: /wetty_containerhost/ssh/root
